version: '3.8'
services:
  # サービス名はfront
  front:
    # コンテナ名はフロント
    container_name: front
    # ビルドコンテキストはカレントディレクトリ
    build:
      context: .
      dockerfile: Dockerfile_TSReact
      # mode_modules用の永続化Volumeを作成して2回目以降のnode_modulesの呼び出しを高速化
      #- node_modules_volume:/app/node_modules
      # npmを使って起動する
      #command: sh -c "npm start"
    ports:
      # デフォルトの3000ポートを使う
      - "5173:5173"
    # ホットリロードを有効化
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  go:
    container_name: obserbooks-go
    build:
      context: .
      dockerfile: Dockerfile_Go
    depends_on:
      - mysql-db
    ports:
      - 2345:2345
    volumes:
      - ./server:/go/obserbooks
    tty: true
    networks:
      - golang_test_network
  mysql-db:
    container_name: obserbooks-mysql
    build:
      context: .
      dockerfile: Dockerfile_MySQL
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_USER: yuuki
      MYSQL_ROOT_PASSWORD: root2733ek9se3pe
      MYSQL_PASSWORD: 2733ek9se3pe
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - golang_test_network

networks:
  golang_test_network:
