version: '3.8'
services:
  # サービス名はfront
  front:
    # コンテナ名はフロント
    container_name: front
    # ビルドコンテキストはカレントディレクトリ
    build:
      context: .
      dockerfile: Dockerfile_TSReact
      # mode_modules用の永続化Volumeを作成して2回目以降のnode_modulesの呼び出しを高速化
      #- node_modules_volume:/app/node_modules
      # npmを使って起動する
      #command: sh -c "npm start"
    ports:
      # デフォルトの3000ポートを使う
      - "5173:5173"
    # ホットリロードを有効化
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  go:
    build:
      context: .
      dockerfile: Dockerfile_Go
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    stdin_open: true
    tty: true
    volumes:
      - ./Server:/go/src
    networks:
      - golang_test_network
    ports:
      - 8080:8080
  db:
    build:
      context: .
      dockerfile: Dockerfile_MySQL
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    tty: true
    ports:
      - 3306:3306
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./Server/infrastructure/mysql/mysql.env
    volumes:
      - ./Server/infrastructure/mysql:/etc/mysql/conf.d
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./Server/infrastructure/init
        target: /docker-entrypoint-initdb.d
    networks:
      - golang_test_network

volumes:
  mysql-data:
    name: mysql_volume

networks:
  golang_test_network:
