version: '3.8'
services:
  # サービス名はfront
  front:
    # コンテナ名はフロント
    container_name: front
    # ビルドコンテキストはカレントディレクトリ
    build:
      context: .
      dockerfile: Dockerfile_TSReact
      # mode_modules用の永続化Volumeを作成して2回目以降のnode_modulesの呼び出しを高速化
      #- node_modules_volume:/app/node_modules
      # npmを使って起動する
      #command: sh -c "npm start"
    ports:
      # デフォルトの3000ポートを使う
      - "5173:5173"
    # ホットリロードを有効化
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
volumes:
  node_modules_volume:
