package interactors

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	database "obserbooks/infrastructure/mysql"
	repositories "obserbooks/infrastructure/repositories/book"
	"obserbooks/usecases/boundaries"
)

var _ boundaries.BookInputBoundary = &BookInteractor{}

type BookInteractor struct {
	BookRepository *repositories.BookRepository
	db             database.DB
}

func NewBookInteractor(bookRepository *repositories.BookRepository) *BookInteractor {
	return &BookInteractor{
		BookRepository: bookRepository,
	}
}
